export {default as Home} from './Home'
export {default as Cheese} from './Cheese'
export {default as Review} from './Review'
export {default as Survey} from './Survey'
export {default as Login} from './Login'